<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CustomerDetails.aspx.cs" Inherits="DEMOProject.CustomerDetails" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="padding: 20px; width: 400px;">
            <h2>Customer Details</h2>

            <asp:Label ID="lblSrNo" runat="server" Text="Sr. No:"></asp:Label><br />
            <asp:TextBox ID="txtSrNo" runat="server" /><br />
            <br />

            <asp:Label ID="lblCustomerCode" runat="server" Text="Customer Code:"></asp:Label><br />
            <asp:TextBox ID="txtCustomerCode" runat="server" /><br />
            <br />

            <asp:Label ID="lblName" runat="server" Text="Name:"></asp:Label><br />
            <asp:TextBox ID="txtName" runat="server" /><br />
            <br />

            <asp:Label ID="lblAddress" runat="server" Text="Address:"></asp:Label><br />
            <asp:TextBox ID="txtAddress" runat="server" TextMode="MultiLine" Rows="3" /><br />
            <br />

            <asp:Label ID="lblComMobileNo" runat="server" Text="Company Mobile No:"></asp:Label><br />
            <asp:TextBox ID="txtComMobileNo" runat="server" /><br />
            <br />

            <asp:Label ID="lblWebsite" runat="server" Text="Website:"></asp:Label><br />
            <asp:TextBox ID="txtWebsite" runat="server" /><br />
            <br />

            <asp:Label ID="lblState" runat="server" Text="State:"></asp:Label><br />
            <asp:TextBox ID="txtState" runat="server" /><br />
            <br />

            <asp:Label ID="lblCountry" runat="server" Text="Country:"></asp:Label><br />
            <asp:TextBox ID="txtCountry" runat="server" /><br />
            <br />

            <asp:Label ID="lblContactPerson" runat="server" Text="Contact Person:"></asp:Label><br />
            <asp:TextBox ID="txtContactPerson" runat="server" /><br />
            <br />

            <asp:Label ID="lblMobileNo" runat="server" Text="Mobile No:"></asp:Label><br />
            <asp:TextBox ID="txtMobileNo" runat="server" /><br />
            <br />

            <asp:Label ID="lblEmailID" runat="server" Text="Email ID:"></asp:Label><br />
            <asp:TextBox ID="txtEmailID" runat="server" /><br />
            <br />


            <asp:Label ID="RateContract" runat="server" Text="Rate Contract:"></asp:Label><br />
            <asp:DropDownList ID="ddlRateContract" runat="server" Width="124px">
                <asp:ListItem Text="-- Select --" Value="" />
                <asp:ListItem Text="Yes" Value="Yes" />
                <asp:ListItem Text="No" Value="No" />
            </asp:DropDownList>
            <br />
            <br />


            <asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click" />
            <br />
            <br />

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True"
                AutoGenerateDeleteButton="True"
                OnRowEditing="GridView1_RowEditing"
                OnRowUpdating="GridView1_RowUpdating"
                OnRowCancelingEdit="GridView1_RowCancelingEdit"
                OnRowDeleting="GridView1_RowDeleting"
                DataKeyNames="Id">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                    <asp:BoundField DataField="SrNo" HeaderText="Sr No" />
                    <asp:BoundField DataField="CustomerCode" HeaderText="Customer Code" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Address" HeaderText="Address" />
                    <asp:BoundField DataField="CompanyMobileNo" HeaderText="Company Mobile No." />
                    <asp:BoundField DataField="Website" HeaderText="Website" />
                    <asp:BoundField DataField="State" HeaderText="State" />
                    <asp:BoundField DataField="Country" HeaderText="Country" />
                    <asp:BoundField DataField="ContactPerson" HeaderText="ContactPerson" />
                    <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" />
                    <asp:BoundField DataField="EmailID" HeaderText="EmailID" />
                    <asp:BoundField DataField="RateContract" HeaderText="RateContract" />

                    <%--<asp:TemplateField HeaderText="Actions">
                        <ItemTemplate>
                            <asp:LinkButton ID="lnkEdit" runat="server" CommandName="Edit" CommandArgument='<%# Eval("id") %>'>Edit</asp:LinkButton>
                            <asp:LinkButton ID="lnkDelete" runat="server" CommandName="Delete" CommandArgument='<%# Eval("id") %>'
                                OnClientClick="return confirm('Are you sure you want to delete this employee?');">Delete</asp:LinkButton>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:LinkButton ID="lnkUpdate" runat="server" CommandName="Update" CommandArgument='<%# Eval("id") %>'>Update</asp:LinkButton>
                            <asp:LinkButton ID="lnkCancel" runat="server" CommandName="Cancel" CommandArgument='<%# Eval("id") %>'>Cancel</asp:LinkButton>
                        </EditItemTemplate>
                    </asp:TemplateField>--%>
                </Columns>
            </asp:GridView>

            <%--<asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>--%>
        </div>
    </form>
</body>
</html>
